apiVersion: v1
kind: Pod
metadata:
  name: nginx-app
spec:
  containers:
    - name: nginx-app
      image: nginx
      env:
        # Env var defined in my-config Config Map
        - name: ENVIRONMENT
          valueFrom:
            configMapKeyRef:
              name: my-config
              key: env
        # Env var defined in my-config Config Map
        - name: LOG_LEVEL
          valueFrom:
            configMapKeyRef:
              name: my-config
              key: log_level
      volumeMounts:
        # Mount Config Map volume to pod
        - name: config-volume
          mountPath: /config
        # Mount Secret volume to pod
        - name: secret-volume
          mountPath: /secret
          readOnly: true
  volumes:
    # Config Map volume
    - name: config-volume
      configMap:
        name: my-config
    # Secret volume
    - name: secret-volume
      secret:
        secretName: my-secrets